version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: tse_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tse_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: tse_backend
    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tse_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000

    volumes:
      - ./backend:/app


  pgadmin:
    image: dpage/pgadmin4
    container_name: tse_pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tse.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
